COMPANIES = [
    {"company": "Stripe", "ats": "greenhouse", "slug": "stripe"},
    {"company": "Databricks", "ats": "greenhouse", "slug": "databricks"},
    {"company": "Scale AI", "ats": "greenhouse", "slug": "scaleai"},
    {"company": "Anthropic", "ats": "greenhouse", "slug": "anthropic"},
    {"company": "Reddit", "ats": "greenhouse", "slug": "reddit"},
    {"company": "Figma", "ats": "greenhouse", "slug": "figma"},
    {"company": "Roblox", "ats": "greenhouse", "slug": "roblox"},
    {"company": "Brex", "ats": "greenhouse", "slug": "brex"},
    {"company": "Robinhood", "ats": "greenhouse", "slug": "robinhood"},
    {"company": "Samsara", "ats": "greenhouse", "slug": "samsara"},
    {"company": "Affirm", "ats": "greenhouse", "slug": "affirm"},
    {"company": "Vercel", "ats": "greenhouse", "slug": "vercel"},
    {"company": "Tailscale", "ats": "greenhouse", "slug": "tailscale"},
    {"company": "Cloudflare", "ats": "greenhouse", "slug": "cloudflare"},
    {"company": "GitLab", "ats": "greenhouse", "slug": "gitlab"},
    {"company": "Twilio", "ats": "greenhouse", "slug": "twilio"},
    {"company": "Discord", "ats": "greenhouse", "slug": "discord"},
    {"company": "Airbnb", "ats": "greenhouse", "slug": "airbnb"},
    {"company": "Instacart", "ats": "greenhouse", "slug": "instacart"},
    {"company": "Pinterest", "ats": "greenhouse", "slug": "pinterest"},
    {"company": "Lyft", "ats": "greenhouse", "slug": "lyft"},
    {"company": "Oscar Health", "ats": "greenhouse", "slug": "oscar"},
    {"company": "Gusto", "ats": "greenhouse", "slug": "gusto"},
    {"company": "Chime", "ats": "greenhouse", "slug": "chime"},
    {"company": "Flexport", "ats": "greenhouse", "slug": "flexport"},
    {"company": "Faire", "ats": "greenhouse", "slug": "faire"},
    {"company": "Airtable", "ats": "greenhouse", "slug": "airtable"},
    {"company": "Asana", "ats": "greenhouse", "slug": "asana"},
    {"company": "Okta", "ats": "greenhouse", "slug": "okta"},
    {"company": "MongoDB", "ats": "greenhouse", "slug": "mongodb"},
    {"company": "Elastic", "ats": "greenhouse", "slug": "elastic"},
    {"company": "Amplitude", "ats": "greenhouse", "slug": "amplitude"},
    {"company": "Calendly", "ats": "greenhouse", "slug": "calendly"},
    {"company": "Webflow", "ats": "greenhouse", "slug": "webflow"},
    {"company": "Motive", "ats": "greenhouse", "slug": "motive"},
    {"company": "Glean", "ats": "greenhouse", "slug": "gleanwork"},
    {"company": "CircleCI", "ats": "greenhouse", "slug": "circleci"},
    {"company": "Maven Clinic", "ats": "greenhouse", "slug": "mavenclinic"},
    {"company": "Duolingo", "ats": "greenhouse", "slug": "duolingo"},
    {"company": "Nuro", "ats": "greenhouse", "slug": "nuro"},
    {"company": "Waymo", "ats": "greenhouse", "slug": "waymo"},
    {"company": "Fivetran", "ats": "greenhouse", "slug": "fivetran"},
    {"company": "DataDog", "ats": "greenhouse", "slug": "datadog"},
    {"company": "Netflix", "ats": "lever", "slug": "netflix"},
    {"company": "Ashby", "ats": "ashby", "slug": "Ashby"},
    {"company": "Linear", "ats": "ashby", "slug": "Linear"},
    {"company": "Perplexity", "ats": "ashby", "slug": "Perplexity"},
    {"company": "Cursor", "ats": "ashby", "slug": "Cursor"},
    {"company": "Mercor", "ats": "ashby", "slug": "Mercor"},
    {"company": "Replit", "ats": "ashby", "slug": "replit"},
    {"company": "Harvey", "ats": "ashby", "slug": "Harvey"},
    {"company": "Runway", "ats": "ashby", "slug": "Runway"},
    {"company": "Writer", "ats": "ashby", "slug": "Writer"},
    {"company": "Modal", "ats": "ashby", "slug": "Modal"},
    {"company": "Vanta", "ats": "ashby", "slug": "Vanta"},
    {"company": "Watershed", "ats": "ashby", "slug": "Watershed"},
    {"company": "ElevenLabs", "ats": "ashby", "slug": "elevenlabs"},
    {"company": "LangChain", "ats": "ashby", "slug": "LangChain"},
    {"company": "Abridge", "ats": "ashby", "slug": "Abridge"},
    {"company": "Zapier", "ats": "ashby", "slug": "Zapier"},
    {"company": "Supabase", "ats": "ashby", "slug": "Supabase"},
    # Verified public boards added to broaden sector and company coverage.
    {"company": "Dropbox", "ats": "greenhouse", "slug": "dropbox"},
    {"company": "Klaviyo", "ats": "greenhouse", "slug": "klaviyo"},
    {"company": "Checkr", "ats": "greenhouse", "slug": "checkr"},
    {"company": "Mixpanel", "ats": "greenhouse", "slug": "mixpanel"},
    {"company": "dbt Labs", "ats": "greenhouse", "slug": "dbtlabsinc"},
    {"company": "Grafana Labs", "ats": "greenhouse", "slug": "grafanalabs"},
    {"company": "Postman", "ats": "greenhouse", "slug": "postman"},
    {"company": "LaunchDarkly", "ats": "greenhouse", "slug": "launchdarkly"},
    {"company": "Notion", "ats": "ashby", "slug": "Notion"},
    {"company": "Ramp", "ats": "ashby", "slug": "Ramp"},
    {"company": "Spotify", "ats": "lever", "slug": "spotify"},
    {"company": "DoorDash", "ats": "greenhouse", "slug": "doordashusa"},
    {"company": "Toast", "ats": "greenhouse", "slug": "toast"},
    {"company": "Squarespace", "ats": "greenhouse", "slug": "squarespace"},
    {"company": "Tripadvisor", "ats": "greenhouse", "slug": "tripadvisor"},
    {"company": "Block", "ats": "greenhouse", "slug": "block"},
    {"company": "SoFi", "ats": "greenhouse", "slug": "sofi"},
    {"company": "Intercom", "ats": "greenhouse", "slug": "intercom"},
    {"company": "Box", "ats": "greenhouse", "slug": "boxinc"},
    {"company": "Smartsheet", "ats": "greenhouse", "slug": "smartsheet"},
    {"company": "Twitch", "ats": "greenhouse", "slug": "twitch"},
    {"company": "Plaid", "ats": "ashby", "slug": "Plaid"},
    {"company": "Patreon", "ats": "ashby", "slug": "Patreon"},
]
